CREATE TABLE LINK (
  ID_LINK NUMBER(38,0) CONSTRAINT LINK_ID_NN NOT NULL,
  URL VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  ID_USER NUMBER(38, 0),
  PRIMARY KEY (ID_LINK),
  FOREIGN KEY (ID_USER) REFERENCES USER (ID_USER)
);

INSERT INTO LINK(ID_LINK, URL, DESCRIPTION, ID_USER)
VALUES (1, 'http://javaworld.com', 'Last news from Java', 1);

INSERT INTO LINK(ID_LINK, URL, DESCRIPTION, ID_USER)
VALUES (2, 'http://dzone.com', 'More last news from Java', 1);